### ISSUE TITLE
Use a different token other than `'` for referencing rust values

### ISSUE THREAD

**Issue by ColonelThirtyTwo** [dronesforwork/inline-python#4]
Currently the crate uses `'` to denote rust variables, which conflicts with single quoted strings. To be more compatible, the crate should use a token that Python does not use to denote rust variables, such as `!`.

**Comment by m-ou-se** [comment]
Not supporting single quoted strings has nothing to do with using `'var` as placeholders. The crate doesn't support single quoted strings of multiple characters, simply because the Rust tokenizer considers `'a'` a character literal, and will therefore reject `'abc'`. `'a'` works fine, and is parsed very differently from `'a`.
